name: nvidia-tegra-igx-kernel
adopt-info: kernel
grade: stable
summary: nvidia-tegra-igx linux kernel
description: The nvidia-tegra-igx Ubuntu kernel package as a snap
type: kernel
confinement: strict
build-base: core22

architectures:
  - build-on: [arm64]
    build-for: [arm64]

parts:
  kernel:
    # Need .ko.zst support from u23.10 for backport
    source: https://git.launchpad.net/~canonical-kernel-snaps/+git/kernel-snaps-u23.10
    source-type: git
    source-branch: main
    plugin: nil
    override-pull: |
      craftctl default
      craftctl set version="$(apt show linux-image-uc-nvidia-tegra-igx 2>/dev/null | sed -n 's/^Version: //p' | head -n1)"
    build-packages:
      - kmod
    stage-packages:
      - linux-image-uc-nvidia-tegra-igx
    organize:
      boot: ./
      lib/firmware: firmware
      lib/modules: modules
      usr/share/doc: doc
    override-build: |
      # Move kernel.efi
      mv "$CRAFT_PART_INSTALL"/boot/kernel.efi-* "$CRAFT_PART_INSTALL"/boot/kernel.efi
      # Update depmod
      depmod -b "$CRAFT_PART_INSTALL" $(basename "$CRAFT_PART_INSTALL"/lib/modules/*)
      # Trim firmware
      ls "$CRAFT_PART_INSTALL"/lib
      ls "$CRAFT_PART_INSTALL"/lib/firmware/
      bash -eux "$CRAFT_PART_SRC"/trim-firmware "$CRAFT_PART_INSTALL"/lib
      craftctl default
