name: pc-kernel
adopt-info: kernel
grade: stable
summary: generic linux kernel
description: The generic Ubuntu kernel package as a snap
type: kernel
confinement: strict
build-base: core22
# In addition to these repositories, the /+snap/ page on launchpad may
# also build with ESM repositories enabled, or built in a particular
# PPA, which will also be used.
package-repositories:
  - type: apt
    ppa: canonical-kernel-team/uc20-release
  - type: apt
    ppa: canonical-kernel-team/uc20-staging
  - type: apt
    ppa: canonical-kernel-team/proposed

parts:
  kernel:
    plugin: nil
    # Set this snap version to the meta version of the package used to
    # provide kernel.efi / vmlinuz
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(apt show linux-image-uc22-generic 2>/dev/null | sed -n 's/^Version: //p' | head -n1)"
    build-packages:
      - kmod
    stage-packages:
      - linux-image-uc22-generic
    organize:
      boot: ./
      lib/firmware: firmware
      lib/modules: modules
      usr/share/doc: doc
    override-build: |
      if [ -e "$SNAPCRAFT_PART_INSTALL"/usr/share/doc/linux-image-uc22-generic/kernelefi.stamp ]; then
        rm -vf "$SNAPCRAFT_PART_INSTALL"/boot/vmlinuz-*
      else
        mv "$SNAPCRAFT_PART_INSTALL"/boot/vmlinuz-* "$SNAPCRAFT_PART_INSTALL"/boot/vmlinuz
      fi
      if [ -d "$SNAPCRAFT_PART_INSTALL"/usr/share/doc/linux-signatures-nvidia-*-generic ]; then
        cd "$SNAPCRAFT_PART_INSTALL"/lib/modules/*/kernel/nvidia-470srv/bits
        sh BUILD
        # Update depmod
        depmod -b "$SNAPCRAFT_PART_INSTALL" $(basename "$SNAPCRAFT_PART_INSTALL"/lib/modules/*)
        # Clean nvidia modules
        sh CLEAN
      else
        # Update depmod
        depmod -b "$SNAPCRAFT_PART_INSTALL" $(basename "$SNAPCRAFT_PART_INSTALL"/lib/modules/*)
      fi
      snapcraftctl build
    # Exclude transitive dependencies of userspace stage-packages that
    # do not make sense in the kernel snap. E.g. iw tool is shipped in
    # base snap, but kernel needs to ship regulatory-db datafiles
    # alone.
    stage:
      - -etc
      - -lib
      - -usr
      - -sbin
      # Exclude current and future, but 470srv
      - -modules/*/kernel/nvidia-*0
      - -modules/*/kernel/nvidia-*5
      - -modules/*/kernel/nvidia-4[156][08]srv
      - -modules/*/kernel/nvidia-5*srv
      - -doc/crda
      - -doc/iw
      - -doc/linux-base
      - -doc/binutils*
      - -doc/libbinutils
      - -doc/libctf-nobfd0
      - -doc/libctf0
      - -doc/libpciaccess0
      - -doc/nvidia-kernel-common-*
    override-stage: |
      snapcraftctl stage
      # Check that only one nvidia series got shipped
      if [ "$SNAPCRAFT_TARGET_ARCH" = "amd64" ]; then
        [ $(ls "$SNAPCRAFT_STAGE"/modules/*/kernel | grep nvidia | wc -l) -eq 1 ]
      fi
