name: pc-kernel
version: 5.4.0-81.91.1
summary: generic linux kernel
description: The generic Ubuntu kernel package as a snap
type: kernel
confinement: strict
build-base: core20

parts:
  kernel:
    source: git://git.launchpad.net/~canonical-kernel-snaps/+git/kernel-snaps-uc20
    source-type: git
    source-branch: master
    plugin: make
    build-environment:
      - on amd64:
          - KERNEL_IMAGE_FORMAT: efi
      - else:
          - KERNEL_IMAGE_FORMAT: vmlinuz
    make-parameters:
      - KERNEL_SOURCE=focal:linux-uc20-efi
      - KERNEL=linux-pc-image
      - PROPOSED=true
    build-packages:
      - debootstrap
      - gnupg
      - kmod
      - lsb-release
