name: pc-kernel
version: 5.4.0-80.90.1
summary: generic linux kernel
description: The generic Ubuntu kernel package as a snap
type: kernel
confinement: strict
build-base: core20

parts:
  kernel:
    source: git://git.launchpad.net/~canonical-kernel-snaps/+git/kernel-snaps-uc20
    source-type: git
    source-branch: master
    plugin: make
    make-parameters:
      - KERNEL_SOURCE=focal:linux-uc20-efi
      - KERNEL=linux-pc-image
      - KERNEL_IMAGE_FORMAT=$(if $(filter x86_64,$(shell uname -a)),efi,vmlinuz)
      - PROPOSED=true
    build-packages:
      - debootstrap
      - gnupg
      - kmod
      - lsb-release
