name: pi2-kernel
version: 4.4.0-1030-3
summary: The canonical raspi2 armhf kernel
description: The Ubuntu linux-raspi2 kernel package as a snap
type: kernel
confinement: strict

parts:
  kernel:
    source: lp:~snappy-dev/kernel-snap-makefile/trunk
    plugin: make
    build-packages:
      - debootstrap
      - lsb-release
